import { dunggeunmo } from '@/fonts';
import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${dunggeunmo.variable} text-screen-green font-dunggeunmo`}>{children}</body>
    </html>
  );
}
